/* DOT NOT EDIT. Code generated by /home/remy/workspace/libarch/tests-core/gen-tests.sh. /home/remy/workspace/libarch */


#include <stdio.h>

/* The CUnit test library header. */
#include <CuTest.h>


extern void    Testgdt_create_with_null_pointer(CuTest*);
extern void    Testgdt_create(CuTest*);
extern void    Testgdt_destroy_with_null_pointer(CuTest*);
extern void    Testgdt_destroy(CuTest*);
extern void    Testgdt_add_entry_with_null_context(CuTest*);
extern void    Testgdt_add_entry_with_null_index(CuTest*);
extern void    Testgdt_add_entry_with_null_invalid_size(CuTest*);
extern void    Testgdt_add_entry(CuTest*);
extern void    Testgdt_add_entry_at_with_null_context(CuTest*);
extern void    Testgdt_add_entry_at_with_invalid_size(CuTest*);
extern void    Testgdt_add_entry_at_invalid_index(CuTest*);
extern void    Testgdt_add_entry_at(CuTest*);
extern void    Testgdt_add_entry_at_with_already_used_entry(CuTest*);
extern void    Testgdt_remove_entry_with_null_context(CuTest*);
extern void    Testgdt_remove_entry_forbiden(CuTest*);
extern void    Testgdt_remove_entry_already_free(CuTest*);
extern void    Testgdt_remove_entry(CuTest*);
extern void    Testidt_create_with_null_pointer(CuTest*);
extern void    Testidt_create(CuTest*);
extern void    Testidt_destroy_with_null_pointer(CuTest*);
extern void    Testidt_destroy(CuTest*);
extern void    Testidt_add_entry_with_null_context(CuTest*);
extern void    Testidt_add_entry_with_null_index(CuTest*);
extern void    Testidt_add_entry_with_null_handler(CuTest*);
extern void    Testidt_add_entry(CuTest*);
extern void    Testidt_add_entry_at_with_null_context(CuTest*);
extern void    Testidt_add_entry_at_with_null_handler(CuTest*);
extern void    Testidt_add_entry_at(CuTest*);
extern void    Testidt_add_entry_at_with_already_used_entry(CuTest*);
extern void    Testidt_remove_entry_with_null_context(CuTest*);
extern void    Testidt_remove_entry_already_free(CuTest*);
extern void    Testidt_remove_entry(CuTest*);
extern void    Testldt_create_with_null_pointer(CuTest*);
extern void    Testldt_create(CuTest*);
extern void    Testldt_destroy_with_null_pointer(CuTest*);
extern void    Testldt_destroy(CuTest*);
extern void    Testldt_add_entry_with_null_context(CuTest*);
extern void    Testldt_add_entry_with_null_index(CuTest*);
extern void    Testldt_add_entry_with_null_invalid_size(CuTest*);
extern void    Testldt_add_entry(CuTest*);
extern void    Testldt_add_entry_at_with_null_context(CuTest*);
extern void    Testldt_add_entry_at_with_invalid_size(CuTest*);
extern void    Testldt_add_entry_at(CuTest*);
extern void    Testldt_add_entry_at_with_already_used_entry(CuTest*);
extern void    Testldt_remove_entry_with_null_context(CuTest*);
extern void    Testldt_remove_entry_already_free(CuTest*);
extern void    Testldt_remove_entry(CuTest*);


void RunAllTests(void) 
{

   CuString *output_arch_i386 = CuStringNew();
    CuSuite* suite_arch_i386 = CuSuiteNew();

    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_create_with_null_pointer);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_create);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_destroy_with_null_pointer);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_destroy);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_add_entry_with_null_context);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_add_entry_with_null_index);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_add_entry_with_null_invalid_size);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_add_entry);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_add_entry_at_with_null_context);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_add_entry_at_with_invalid_size);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_add_entry_at_invalid_index);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_add_entry_at);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_add_entry_at_with_already_used_entry);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_remove_entry_with_null_context);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_remove_entry_forbiden);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_remove_entry_already_free);
    SUITE_ADD_TEST(suite_arch_i386,     Testgdt_remove_entry);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_create_with_null_pointer);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_create);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_destroy_with_null_pointer);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_destroy);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_add_entry_with_null_context);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_add_entry_with_null_index);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_add_entry_with_null_handler);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_add_entry);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_add_entry_at_with_null_context);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_add_entry_at_with_null_handler);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_add_entry_at);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_add_entry_at_with_already_used_entry);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_remove_entry_with_null_context);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_remove_entry_already_free);
    SUITE_ADD_TEST(suite_arch_i386,     Testidt_remove_entry);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_create_with_null_pointer);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_create);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_destroy_with_null_pointer);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_destroy);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_add_entry_with_null_context);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_add_entry_with_null_index);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_add_entry_with_null_invalid_size);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_add_entry);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_add_entry_at_with_null_context);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_add_entry_at_with_invalid_size);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_add_entry_at);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_add_entry_at_with_already_used_entry);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_remove_entry_with_null_context);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_remove_entry_already_free);
    SUITE_ADD_TEST(suite_arch_i386,     Testldt_remove_entry);

    CuSuiteRun(suite_arch_i386);
    printf("arch_i386 test results:\n");
    CuSuiteSummary(suite_arch_i386, output_arch_i386);
    CuSuiteDetails(suite_arch_i386, output_arch_i386);
    printf("%s\n", output_arch_i386->buffer);

}

int main(void)
{
    RunAllTests();
    return (0);
}

