/* DOT NOT EDIT. Code generated by /home/remy/workspace/ExAmour/tests-core/gen-tests.sh. /home/remy/workspace/ExAmour */


#include <stdio.h>

/* The CUnit test library header. */
#include <CuTest.h>


extern void Testexamem_hdr_mem_blk_get(CuTest*);
extern void Testexamem_hdr_mem_blk_get_with_invalid_pointer(CuTest*);
extern void Testexamem_hdr_mem_blk_free(CuTest*);
extern void Testexamem_hdr_mem_blk_rationalize(CuTest*);
extern void Testexamem_hdr_mem_blk_free_with_invalid_pointer(CuTest*);
extern void    Testexamem_mem_blk_ref_by_size(CuTest*);
extern void    Testexamem_mem_blk_ref_by_size_with_invalid_size(CuTest*);
extern void    Testexamem_mem_blk_ref_by_size_with_invalid_flags(CuTest*);
extern void    Testexamem_mem_blk_ref_by_size_with_8b_alignment(CuTest*);
extern void    Testexamem_mem_blk_ref_by_size_with_16b_alignment(CuTest*);
extern void    Testexamem_mem_blk_ref_by_size_with_4kb_alignment(CuTest*);
extern void    Testexamem_mem_blk_ref_by_size_with_4mb_alignment(CuTest*);
extern void    Testexamem_mem_blk_ref_by_address(CuTest*);
extern void    Testexamem_mem_blk_ref_by_address_with_invalid_addr(CuTest*);
extern void    Testexamem_mem_blk_ref_by_address_with_invalid_size(CuTest*);
extern void    Testexamem_mem_blk_ref_by_address_with_invalid_flags(CuTest*);
extern void    Testexamem_mem_blk_unref(CuTest*);
extern void    Testexamem_mem_blk_unref_with_invalid_value(CuTest*);
extern void    Testexamem_init(CuTest*);
extern void Testexaprocess(CuTest*);
extern void Testexaevent(CuTest*);
extern void Test_exabus_init_with_null_inf(CuTest*);
extern void Test_exabus_init(CuTest*);
extern void Testexabus_publish_with_null_path(CuTest*);
extern void Testexabus_publish_with_null_interface_name(CuTest*);
extern void Testexabus_publish_with_null_interface(CuTest*);
extern void Testexabus_publish_with_null_interface_symbols(CuTest*);
extern void Testexabus_publish_with_null_interface_symbol_id(CuTest*);
extern void Testexabus_publish(CuTest*);
extern void Testexabus_publish_already_existing_interface(CuTest*);
extern void Testexabus_unpublish_with_null_fullpath(CuTest*);
extern void Testexabus_unpublish_with_invalid_fullpath(CuTest*);
extern void Testexabus_unpublish(CuTest*);
extern void Testexabus_find_with_null_fullpath(CuTest*);
extern void Testexabus_find_with_null_symbol_and_invalid_fullpath(CuTest*);
extern void Testexabus_find_with_null_symbol_and_valid_fullpath(CuTest*);
extern void Testexabus_find_with_invalid_symbol_and_valid_fullpath(CuTest*);
extern void Testexabus_find_with_valid_symbol_and_valid_fullpath_and_invalid_type(CuTest*);
extern void Testexabus_find_with_valid_symbol_and_valid_fullpath_and_valid_type(CuTest*);
extern void Testexabus_find_with_valid_symbol_and_valid_fullpath_and_first_valid_type_of_two_same_name_symbol(CuTest*);
extern void Testexabus_find_with_valid_symbol_and_valid_fullpath_and_second_valid_type_of_two_same_name_symbol(CuTest*);
extern void Testexabus_suscribe_with_null_fullpath(CuTest*);
extern void Testexabus_suscribe_with_null_signal_and_invalid_fullpath(CuTest*);
extern void Testexabus_suscribe_with_null_signal_and_valid_fullpath(CuTest*);
extern void Testexabus_suscribe_with_invalid_signal_and_valid_fullpath(CuTest*);
extern void Testexabus_suscribe_with_valid_signal_and_valid_fullpath(CuTest*);
extern void Testexabus_suscribe_with_valid_signal_and_valid_fullpath_with_signal_same_name_as_a_method(CuTest*);
extern void Testexabus_unsuscribe_with_null_fullpath(CuTest*);
extern void Testexabus_unsuscribe_with_null_signal_and_invalid_fullpath(CuTest*);
extern void Testexabus_unsuscribe_with_invalid_signal_and_invalid_fullpath(CuTest*);
extern void Testexabus_unsuscribe_with_valid_signal_and_invalid_fullpath(CuTest*);
extern void Testexabus_unsuscribe_with_valid_signal_and_valid_fullpath(CuTest*);
extern void Testexabus_raise_with_null_fullpath(CuTest*);
extern void Testexabus_raise_with_null_signal_and_invalid_fullpath(CuTest*);
extern void Testexabus_raise_with_invalid_signal_and_invalid_fullpath(CuTest*);
extern void Testexabus_raise_with_valid_signal_and_invalid_fullpath(CuTest*);
extern void Testexabus_raise_with_valid_signal_and_valid_fullpath(CuTest*);
extern void Testexabus_call_with_null_fullpath(CuTest*);
extern void Testexabus_call_with_null_method_and_invalid_fullpath(CuTest*);
extern void Testexabus_call_with_invalid_method_and_invalid_fullpath(CuTest*);
extern void Testexabus_call_with_valid_method_and_invalid_fullpath(CuTest*);
extern void Testexabus_call_with_valid_method_and_valid_fullpath(CuTest*);


void RunAllTests(void)
{

   CuString *output_examem = CuStringNew();
    CuSuite* suite_examem = CuSuiteNew();
   CuString *output_exaprocess = CuStringNew();
    CuSuite* suite_exaprocess = CuSuiteNew();
   CuString *output_exaevent = CuStringNew();
    CuSuite* suite_exaevent = CuSuiteNew();
   CuString *output_exaboot = CuStringNew();
    CuSuite* suite_exaboot = CuSuiteNew();
   CuString *output_exabus = CuStringNew();
    CuSuite* suite_exabus = CuSuiteNew();

    SUITE_ADD_TEST(suite_examem,     Testexamem_init);
    SUITE_ADD_TEST(suite_examem,  Testexamem_hdr_mem_blk_get);
    SUITE_ADD_TEST(suite_examem,  Testexamem_hdr_mem_blk_get_with_invalid_pointer);
    SUITE_ADD_TEST(suite_examem,  Testexamem_hdr_mem_blk_free);
    SUITE_ADD_TEST(suite_examem,  Testexamem_hdr_mem_blk_rationalize);
    SUITE_ADD_TEST(suite_examem,  Testexamem_hdr_mem_blk_free_with_invalid_pointer);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_ref_by_size);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_ref_by_size_with_invalid_size);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_ref_by_size_with_invalid_flags);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_ref_by_size_with_8b_alignment);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_ref_by_size_with_16b_alignment);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_ref_by_size_with_4kb_alignment);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_ref_by_size_with_4mb_alignment);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_ref_by_address);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_ref_by_address_with_invalid_addr);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_ref_by_address_with_invalid_size);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_ref_by_address_with_invalid_flags);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_unref);
    SUITE_ADD_TEST(suite_examem,     Testexamem_mem_blk_unref_with_invalid_value);

    SUITE_ADD_TEST(suite_exaprocess,  Testexaprocess);

    SUITE_ADD_TEST(suite_exaevent,  Testexaevent);


    SUITE_ADD_TEST(suite_exabus,  Test_exabus_init_with_null_inf);
    SUITE_ADD_TEST(suite_exabus,  Test_exabus_init);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_publish_with_null_path);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_publish_with_null_interface_name);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_publish_with_null_interface);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_publish_with_null_interface_symbols);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_publish_with_null_interface_symbol_id);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_publish);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_publish_already_existing_interface);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_unpublish_with_null_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_unpublish_with_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_unpublish);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_find_with_null_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_find_with_null_symbol_and_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_find_with_null_symbol_and_valid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_find_with_invalid_symbol_and_valid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_find_with_valid_symbol_and_valid_fullpath_and_invalid_type);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_find_with_valid_symbol_and_valid_fullpath_and_valid_type);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_find_with_valid_symbol_and_valid_fullpath_and_first_valid_type_of_two_same_name_symbol);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_find_with_valid_symbol_and_valid_fullpath_and_second_valid_type_of_two_same_name_symbol);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_suscribe_with_null_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_suscribe_with_null_signal_and_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_suscribe_with_null_signal_and_valid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_suscribe_with_invalid_signal_and_valid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_suscribe_with_valid_signal_and_valid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_suscribe_with_valid_signal_and_valid_fullpath_with_signal_same_name_as_a_method);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_unsuscribe_with_null_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_unsuscribe_with_null_signal_and_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_unsuscribe_with_invalid_signal_and_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_unsuscribe_with_valid_signal_and_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_unsuscribe_with_valid_signal_and_valid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_raise_with_null_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_raise_with_null_signal_and_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_raise_with_invalid_signal_and_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_raise_with_valid_signal_and_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_raise_with_valid_signal_and_valid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_call_with_null_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_call_with_null_method_and_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_call_with_invalid_method_and_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_call_with_valid_method_and_invalid_fullpath);
    SUITE_ADD_TEST(suite_exabus,  Testexabus_call_with_valid_method_and_valid_fullpath);

    CuSuiteRun(suite_examem);
    printf("examem test results:\n");
    CuSuiteSummary(suite_examem, output_examem);
    CuSuiteDetails(suite_examem, output_examem);
    printf("%s\n", output_examem->buffer);

    CuSuiteRun(suite_exaprocess);
    printf("exaprocess test results:\n");
    CuSuiteSummary(suite_exaprocess, output_exaprocess);
    CuSuiteDetails(suite_exaprocess, output_exaprocess);
    printf("%s\n", output_exaprocess->buffer);

    CuSuiteRun(suite_exaevent);
    printf("exaevent test results:\n");
    CuSuiteSummary(suite_exaevent, output_exaevent);
    CuSuiteDetails(suite_exaevent, output_exaevent);
    printf("%s\n", output_exaevent->buffer);

    CuSuiteRun(suite_exaboot);
    printf("exaboot test results:\n");
    CuSuiteSummary(suite_exaboot, output_exaboot);
    CuSuiteDetails(suite_exaboot, output_exaboot);
    printf("%s\n", output_exaboot->buffer);

    CuSuiteRun(suite_exabus);
    printf("exabus test results:\n");
    CuSuiteSummary(suite_exabus, output_exabus);
    CuSuiteDetails(suite_exabus, output_exabus);
    printf("%s\n", output_exabus->buffer);

}

int main(void)
{
    RunAllTests();
    return (0);
}

