#!/usr/bin/env bash

# Warning, only for i386.

if [ "$1" == "" ];
then
    echo "Usage: $0 <root path to scan.>"
    echo "Please note that the root path is the libarch project root path."
    echo "Data scanned are written in the test-core/Alltests.c file."
    exit;
fi

DIRS="`find $1 -maxdepth 1 -type d -name 'arch-*' -printf \"%h/%f \"`"
OUTPUT="$1/tests-core/AllTests.c"

echo "/* DOT NOT EDIT. Code generated by $0. $1 */


#include <stdio.h>

/* The CUnit test library header. */
#include <CuTest.h>

" > $OUTPUT

# Each directory is a component... a test suite.
# First, create a full listing of function declaration.
for entry in $DIRS;
do
  TESTS="`find $entry -type d -name 'tests' -printf \"%h/%f \"`"
  for tst in $TESTS;
  do
    cat $tst/*.c | egrep -i "^void[ \t]+test" | 
    sed -e 's/^void//' \
        -e 's/(.*$//' \
        -e 's/$/(CuTest*);/' \
        -e 's/^/extern void/' >> $OUTPUT
  done
done

# Now, create the main function.
echo \
'

void RunAllTests(void) 
{
' >> $OUTPUT

for entry in $DIRS;
do
  suite="`basename $entry | tr '-' '_'`"
  echo \
"   CuString *output_$suite = CuStringNew();
    CuSuite* suite_$suite = CuSuiteNew();" >> $OUTPUT
done

# Add tests.
for entry in $DIRS;
do
  echo >> $OUTPUT
  suite="`basename $entry | tr '-' '_'`"
  TESTS="`find $entry -type d -name 'tests' -printf \"%h/%f \"`"
  for tst in $TESTS;
  do
    cat $tst/*.c | egrep -i '^void[ \t]+test' | 
    sed -e 's/void//' \
        -e 's/(.*$//' \
        -e "s/^/    SUITE_ADD_TEST(suite_$suite, /" \
        -e 's/$/);/' >> $OUTPUT
  done
done

# Run tests.
for entry in $DIRS;
do
  suite="`basename $entry | tr '-' '_'`"
echo \
"
    CuSuiteRun(suite_$suite);
    printf(\"$suite test results:\\n\");
    CuSuiteSummary(suite_$suite, output_$suite);
    CuSuiteDetails(suite_$suite, output_$suite);" >> $OUTPUT
echo "    printf(\"%s\\n\", output_$suite->buffer);" >> $OUTPUT
done

echo \
'
}

int main(void)
{
    RunAllTests();
    return (0);
}
' >> $OUTPUT

